#
# Makefile
# kevin.feng, 2017-05-27 22:43
#


CC = gcc
TARGET = hello_world
CFLAG += 
LDFLAG += 
SRC = main.c
OBJ = main.o 

$(OBJ): $(SRC)
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@


all:
	@echo "Makefile needs your attention"
	$(CC) $(CFLAG) $(LDFLAG) $(OBJ) -o  $(TARGET)


# vim:ft=make
#
